import React from 'react';
import Head from 'next/head';
import styles from '../styles/Rules.module.css';

export default function rules() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Rules.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}
          style={{maxWidth: '70%'}}
        >
          How to Play
        </h1>
        <div className={styles.display_rules}>

        </div>
        <p className={styles.description}>
            
        </p>
      </main>
    </div>
  )
}
